// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protobuf_signer.proto
#ifndef GRPC_protobuf_5fsigner_2eproto__INCLUDED
#define GRPC_protobuf_5fsigner_2eproto__INCLUDED

#include "protobuf_signer.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace grpc_signer {

class SignerCommunication final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_signer.SignerCommunication";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status pullData(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc_signer::SignerDataReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_signer::SignerDataReply>> AsyncpullData(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_signer::SignerDataReply>>(AsyncpullDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_signer::SignerDataReply>> PrepareAsyncpullData(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_signer::SignerDataReply>>(PrepareAsyncpullDataRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_signer::SignerDataReply>* AsyncpullDataRaw(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_signer::SignerDataReply>* PrepareAsyncpullDataRaw(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status pullData(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc_signer::SignerDataReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_signer::SignerDataReply>> AsyncpullData(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_signer::SignerDataReply>>(AsyncpullDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_signer::SignerDataReply>> PrepareAsyncpullData(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_signer::SignerDataReply>>(PrepareAsyncpullDataRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::grpc_signer::SignerDataReply>* AsyncpullDataRaw(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_signer::SignerDataReply>* PrepareAsyncpullDataRaw(::grpc::ClientContext* context, const ::grpc_signer::SignerDataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_pullData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status pullData(::grpc::ServerContext* context, const ::grpc_signer::SignerDataRequest* request, ::grpc_signer::SignerDataReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_pullData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_pullData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_pullData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pullData(::grpc::ServerContext* context, const ::grpc_signer::SignerDataRequest* request, ::grpc_signer::SignerDataReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpullData(::grpc::ServerContext* context, ::grpc_signer::SignerDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpc_signer::SignerDataReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_pullData<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_pullData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_pullData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_pullData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pullData(::grpc::ServerContext* context, const ::grpc_signer::SignerDataRequest* request, ::grpc_signer::SignerDataReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_pullData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_pullData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_pullData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pullData(::grpc::ServerContext* context, const ::grpc_signer::SignerDataRequest* request, ::grpc_signer::SignerDataReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpullData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_pullData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_pullData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::grpc_signer::SignerDataRequest, ::grpc_signer::SignerDataReply>(std::bind(&WithStreamedUnaryMethod_pullData<BaseClass>::StreamedpullData, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_pullData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status pullData(::grpc::ServerContext* context, const ::grpc_signer::SignerDataRequest* request, ::grpc_signer::SignerDataReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedpullData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_signer::SignerDataRequest,::grpc_signer::SignerDataReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_pullData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_pullData<Service > StreamedService;
};

}  // namespace grpc_signer


#endif  // GRPC_protobuf_5fsigner_2eproto__INCLUDED
